[package]
name = "oktaws"
version = "0.10.1"
authors = ["Jonathan Morley <morley.jonathan@gmail.com>"]
description = "Generates temporary AWS credentials with Okta."

[dependencies]
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_str = "0.1"
toml = "0.4"
rusoto_core = "0.34"
rusoto_sts = "0.34"
rusoto_credential = "0.13"
base64 = "0.9"
structopt = "0.2"
structopt-derive = "0.4"
failure = "0.1"
log = "0.4"
keyring = "0.6"
username = "0.2"
dialoguer = "0.1"
sxd-document = "0.2"
sxd-xpath = "0.4"
kuchiki = "0.7"
regex = "1"
serde_ini = "0.1"
path_abs = "0.4"
try_from = "0.2"
glob = "0.2"
walkdir = "2"
rayon = "1"
pretty_env_logger = "0.2"
dirs = "1"
itertools = "0.7"

[target.'cfg(windows)'.dependencies]
rpassword = "2"

[dev-dependencies]
tempfile = "3"
